version: '2.2'

services:
  cloudconfigbus:
    image: kapilshekharraina/cloudconfigbus
    cpu_percent: 10
    mem_reservation: 75m
    #container_name: cloudconfigbus
    environment:
        - cloudconfigbus.activeprofiles=startup, qa
    ports:
      - "8899:8899"
 
networks:
 default:
  external:
   name: ms-chassis-nw