version: '3.2'
services:
  grafana:
    image: grafana/grafana
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 75M
        reservations:
          cpus: '0.10'
          memory: 50M
    #container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret

networks:
 default:
  external:
   name: ms-chassis-nw-swarm