--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: kafka
    broker: "1"
  name: kafka1
spec: 
  ports: 
    - 
      name: http
      port: 9094
      targetPort: 9094
  type: NodePort
  selector: 
    app: kafka
    broker: "1"
    
--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: kafka
    broker: "2"
  name: kafka2
spec: 
  ports: 
    - 
      name: http
      port: 9095
      targetPort: 9095
  type: NodePort
  selector: 
    app: kafka
    broker: "2"