--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: kafka
    broker: b1
  name: kafka1
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: kafka
      broker: b1
  template: 
    metadata: 
      labels: 
        app: kafka
        broker: b1
    spec: 
      containers: 
        - 
          image: "wurstmeister/kafka"
          imagePullPolicy: IfNotPresent
          name: kafka
          ports: 
          - containerPort: 9094
          env:
            - name:  HOSTNAME_COMMAND
              value: "echo $$HOSTNAME"
            - name: PORT_COMMAND
              value: "docker port $$HOSTNAME 9092/tcp | cut -d: -f2"    
            - name: KAFKA_LISTENERS
              value: "INSIDE://_{HOSTNAME_COMMAND}:9092,OUTSIDE://0.0.0.0:9094"   
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INSIDE://kafka1:9092,OUTSIDE://kafka1:9094"   
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INSIDE"   
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"   
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"   
            - name: LOG_CLEANUP_POLICY
              value: "compact"                 
          volumeMounts:
            - mountPath: "/var/run/docker.sock"
              name: dockersock
      volumes:
       - name: dockersock
         hostPath:
            path: "/var/run/docker.sock"
            
--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: kafka
    broker: b2
  name: kafka2
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: kafka
      broker: b2
  template: 
    metadata: 
      labels: 
        app: kafka
        broker: b2
    spec: 
      containers: 
        - 
          image: "wurstmeister/kafka"
          imagePullPolicy: IfNotPresent
          name: kafka
          ports: 
          - containerPort: 9095
          env:
            - name:  HOSTNAME_COMMAND
              value: "echo $$HOSTNAME"
            - name: PORT_COMMAND
              value: "docker port $$HOSTNAME 9092/tcp | cut -d: -f2"    
            - name: KAFKA_LISTENERS
              value: "INSIDE://_{HOSTNAME_COMMAND}:9092,OUTSIDE://0.0.0.0:9095"   
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INSIDE://kafka2:9092,OUTSIDE://kafka2:9095"   
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INSIDE"   
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"   
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"   
            - name: LOG_CLEANUP_POLICY
              value: "compact"                 
          volumeMounts:
            - mountPath: "/var/run/docker.sock"
              name: dockersock
      volumes:
       - name: dockersock
         hostPath:
            path: "/var/run/docker.sock"
            
