version: '3.2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    #container_name: zookeeper
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 50M
        reservations:
          cpus: '0.10'
          memory: 25M
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 75M
        reservations:
          cpus: '0.10'
          memory: 50M 
      replicas: 3      
    #container_name: kafka
    ports:
      - "9094-9096:9094"
      #  published: "9094-9096"
      #  protocol: tcp
        #mode: host
    environment:
      HOSTNAME_COMMAND: "echo $$HOSTNAME"
      PORT_COMMAND: "docker port $$HOSTNAME 9094/tcp | cut -d: -f2"
      KAFKA_LISTENERS: "INSIDE://_{HOSTNAME_COMMAND}:9092,OUTSIDE://0.0.0.0:9094" 
      KAFKA_ADVERTISED_LISTENERS: "INSIDE://_{HOSTNAME_COMMAND}:9092,OUTSIDE://host.kafka:_{PORT_COMMAND}"
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      LOG_CLEANUP_POLICY: compact
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
networks:
 default:
  external:
   name: ms-chassis-nw-swarm
