--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: consul-server
    version: v1
  name: consul-server
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      app: consul-server
      version: v1
  template: 
    metadata: 
      labels: 
        app: consul-server
        version: v1
    spec: 
      containers: 
        - 
          image: consul:latest
          imagePullPolicy: IfNotPresent
          name: consul-server
          command: ["consul"]
          args: ["agent","-server", "-bootstrap-expect", "3","-retry-join","consul-server-bootstrap", "-client", "0.0.0.0","-data-dir","/etc/data"]
          volumeMounts:
            - mountPath: /etc/data
              name: consul-data        
      volumes:
       - name: consul-data
         hostPath:
            path: /work/sharedmount/consul/data
            type: DirectoryOrCreate              

--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: consul-agent
    version: v1
  name: consul-agent
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      app: consul-agent
      version: v1
  template: 
    metadata: 
      labels: 
        app: consul-agent
        version: v1
    spec: 
      containers: 
        - 
          image: consul:latest
          imagePullPolicy: IfNotPresent
          name: consul-agent
          command: ["consul"]
          args: ["agent","-server", "-retry-join","consul-server-bootstrap", "-client", "0.0.0.0","-data-dir","/etc/data"]
          volumeMounts:
            - mountPath: /etc/data
              name: consul-data        
      volumes:
       - name: consul-data
         hostPath:
            path: /work/sharedmount/consul/data
            type: DirectoryOrCreate             