apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage-volume
  labels:
    type: local
spec:
  storageClassName: local-storage-class
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"