version: '3.2'
volumes:
    prometheus_data: {}
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"

networks:
 default:
  external:
   name: ms-chassis-nw