version: '2.2'
services:
  grafana:
    image: grafana/grafana
    cpu_percent: 10
    mem_reservation: 75m
    #container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret

networks:
 default:
  external:
   name: ms-chassis-nw