version: '3.2'

services:
  apigateway:
    image: kapilshekharraina/apigateway
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 75M
        reservations:
          cpus: '0.10'
          memory: 50M
    #container_name: apigateway
    environment:
        - apigateway.activeprofiles=startup, dev
    ports:
      - "8080:8080"
      - "8854:8854"
 
networks:
 default:
  external:
   name: ms-chassis-nw-swarm