version: "2.2"
services:
  mongo:
    image: mongo
    #container_name: mongo
    cpu_percent: 10
    mem_reservation: 150m
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
       #MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo-root
    volumes:
      - ./data:/data/db
    ports:
    - "27017:27017"

networks:
 default:
  external:
   name: ms-chassis-nw