version: '2.2'

services:
  cloudconfigbus:
    image: kapilshekharraina/turbine
    cpu_percent: 10
    mem_reservation: 50m
    #container_name: turbine
    environment:
        - turbine.activeprofiles=startup, qa
    ports:
      - "9093:9093"
      - "8855:8855"
 
networks:
 default:
  external:
   name: ms-chassis-nw