version: '3.2'

services:
  cloudconfigbus:
    image: kapilshekharraina/cloudconfigbus
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 75M
        reservations:
          cpus: '0.10'
          memory: 50M
    environment:
        - cloudconfigbus.activeprofiles=startup, qa
    ports:
      - "8899:8899"
 
networks:
 default:
  external:
   name: ms-chassis-nw-swarm