kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-redis
spec:
  storageClassName: "local-storage-class"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
