---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels: 
    app: redis
    version: v1
  name: redis
spec:
  serviceName: "redis"
  replicas: 1
  selector:
    matchLabels: 
      app: redis
      version: v1
  template:
    metadata: 
      labels: 
        app: redis
        version: v1
    spec:
      containers:
      - name: redis
        image: "bitnami/redis:5.0"
        ports:
        - containerPort: 6379
          name: redis
        env:
        - name:  ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: REDIS_DISABLE_COMMANDS
          value: "FLUSHDB,FLUSHALL"
        volumeMounts:
        - name: redis-data
          mountPath: /bitnami/redis/data
      volumes:
       - name: redis-data
         persistentVolumeClaim: #PVC
          claimName: pvc-redis

