version: '2.2'

services:
  redis:
    image: 'bitnami/redis:5.0'
    #container_name: redis
    mem_reservation: 50M
    mem_limit: 100M
    cpus: ".10"
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'

volumes:
  redis_data:
    driver: local

networks:
 default:
  external:
   name: ms-chassis-nw